### ISSUE TITLE
🙋‍♂️ 支持与反馈: Paste Quick

### ISSUE THREAD

**Issue by chunyang-wen** [jaywcjlove/paste-quick#2]
### 🙋‍♂️ 您需要什么帮助？

无法从 App Store 下载，国区和美区都没法下载。请问在哪个区？

### 💻 桌面

macOS 15.0 (Sequoia)

### ℹ️ 补充说明

点击 README 上的 App Store 下载链接。没法下载。

感谢！

**Comment by jaywcjlove** [comment]
<img width="643" alt="image" src="https://github.com/user-attachments/assets/44beb0bb-1085-4268-a83a-8dd205781fbf">

@chunyang-wen 还在审核被拒绝了 ....

> Guideline 2.1 - Performance - App Completeness
> Issue Description
> 
> The app exhibited one or more bugs that would negatively impact App Store users.
> 
> Bug description:
> 
> Settings > Full Disk Access erroneously states "Granted", however the access was never asked for or granted by the user.
> 
> Next Steps
> 
> Test the app on supported devices to identify and resolve bugs and stability issues before submitting for review.
> 
> If you are unable to reproduce the bug, try the following:
> 
> - For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce.
> - For app updates, install the new version as an update to the previous version, then follow the steps to reproduce.

**Comment by jaywcjlove** [comment]
@chunyang-wen 已发布
